[package]
name = "symbolic-il2cpp"
version = "12.7.1"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
documentation = "https://docs.rs/symbolic-il2cpp"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library for parsing il2cpp line mappings.
"""
edition = "2021"

[dependencies]
indexmap = "2.0.0"
serde_json = "1.0.94"
symbolic-common = { version = "12.7.1", path = "../symbolic-common" }
symbolic-debuginfo = { version = "12.7.1", path = "../symbolic-debuginfo" }
