[package]
name = "symbolic-il2cpp"
version = "8.6.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
documentation = "https://docs.rs/symbolic-il2cpp"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library for parsing il2cpp metadata.
"""
edition = "2021"

[dependencies]
anyhow = "1"
gimli = "0.26"
object = "0.28"
scroll = "0.11"

[dev-dependencies]
memmap2 = "0.5.0"
