[package]
name = "symbolic-il2cpp"
version = "9.0.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
documentation = "https://docs.rs/symbolic-il2cpp"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library for parsing il2cpp metadata.
"""
edition = "2021"

[dependencies]
anyhow = "1"
gimli = "0.26"
indexmap = "1.8.0"
object = "0.28"
scroll = "0.11"
serde_json = "1.0.79"
symbolic-common = { version = "9.0.0", path = "../symbolic-common" }
symbolic-debuginfo = { version = "9.0.0", path = "../symbolic-debuginfo" }
thiserror = "1.0.20"

[dev-dependencies]
memmap2 = "0.5.0"
symbolic-testutils = { path = "../symbolic-testutils" }
