[package]
name = "symbolic-il2cpp"
version = "9.1.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
documentation = "https://docs.rs/symbolic-il2cpp"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library for parsing il2cpp line mappings.
"""
edition = "2021"

[dependencies]
indexmap = "1.8.0"
symbolic-common = { version = "9.1.0", path = "../symbolic-common" }
symbolic-debuginfo = { version = "9.1.0", path = "../symbolic-debuginfo" }
