[package]
name = "symbolic-debuginfo"
version = "2.0.1"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-debuginfo"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to inspect and load DWARF debugging information from binaries, such
as Mach-O or ELF.
"""

[dependencies]
gimli = "0.15"
goblin = "0.0"
if_chain = "0.1"
lazy_static = "1.0"
memmap = "0.5"
regex = "0.2"
scroll = "0.8"
uuid = "0.5"
symbolic-common = { path = "../common", version = "2.0.1", features = ["with_objects", "with_dwarf"] }
