[package]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
name = "symbolic-debuginfo"
version = "1.1.2"

[dependencies]
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0"
if_chain = "0.1"
memmap = "0.5"
scroll = "0.7"
uuid = "0.5"

[dependencies.symbolic-common]
path = "../common"
features = ["with_objects", "with_dwarf"]
