[package]
name = "symbolic-debuginfo"
version = "6.0.6"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-debuginfo"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to inspect and load DWARF debugging information from binaries, such
as Mach-O or ELF.
"""
edition = "2018"

exclude = [
    "tests/**/*",
]

[dependencies]
dmsort = "1.0.0"
failure = "0.1.5"
fallible-iterator = "0.1.6"
flate2 = { version = "1.0.6", features = ["rust_backend"], default-features = false }
gimli = { version = "0.17.0", features = ["read", "std"], default-features = false }
goblin = { git = "https://github.com/m4b/goblin", branch = "master" }
lazycell = "1.2.1"
pdb = "0.4.0"
parking_lot = "0.7.1"
pest = "2.1.0"
pest_derive = "2.1.0"
serde = { version = "1.0.89", optional = true }
smallvec = "0.6.9"
symbolic-common = { version = "6.0.6", path = "../common" }

[dev-dependencies]
insta = "0.7.1"
