[package]
name = "symbolic-debuginfo"
version = "5.8.0"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-debuginfo"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to inspect and load DWARF debugging information from binaries, such
as Mach-O or ELF.
"""
edition = "2018"

[dependencies]
failure = "0.1.3"
flate2 = { version = "1.0.6", features = ["rust_backend"], default-features = false }
goblin = "0.0.19"
lazy_static = "1.2.0"
regex = "1.1.0"
serde = { version = "1.0.80", optional = true }
serde_plain = { version = "0.3.0", optional = true }
symbolic-common = { path = "../common", version = "5.8.0", features = ["with_objects", "with_dwarf"] }
uuid = "0.7.1"

[dev-dependencies]
symbolic-testutils = { version = "5.8.0", path = "../testutils" }

[features]
default = []
with_serde = ["serde", "serde_plain"]
