[package]
name = "symbolic-proguard"
version = "5.2.0"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-proguard"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to process ProGuard mapping files and symbolicate frames from
optimized applications.
"""

[dependencies]
proguard = "1.1.0"
symbolic-common = { version = "5.2.0", path = "../common" }
uuid = "0.7.1"
