[package]
name = "symbolic-demangle"
version = "1.1.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[dependencies]
symbolic-common = { path = "../common" }
rustc-demangle = "0.1"

[build-dependencies]
gcc = "0.3"
