[package]
name = "symcache_debug"
version = "12.15.1"
authors = ["Jan Michael Auer <mail@jauer.org>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
symbolic = { version = "12.15.1", path = "../../symbolic", features = [
    "symcache",
    "demangle",
    "il2cpp",
] }
