[package]
name = "dump_sources"
version = "12.6.0"
authors = ["Jan Michael Auer <mail@jauer.org>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.5"
symbolic = { path = "../../symbolic" }
