[package]
name = "sourcemapcache_debug"
version = "12.0.0"
authors = ["Sentry <hello@sentry.io>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.32"
clap = "3.1.0"
symbolic = { path = "../../symbolic", features = ["sourcemapcache"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
