[package]
name = "symbolic-cfi"
version = "9.0.0"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-cfi"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to process call frame information
"""
edition = "2018"

[dependencies]
symbolic-common = { version = "9.0.0", path = "../symbolic-common" }
symbolic-debuginfo = { version = "9.0.0", path = "../symbolic-debuginfo" }
thiserror = "1.0.20"

[dev-dependencies]
insta = "1.3.0"
symbolic-testutils = { path = "../symbolic-testutils" }
similar-asserts = "1.0.0"
