[package]
name = "debuginfo_debug"
version = "12.17.2"
authors = ["Markus Stange <mstange.moz@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
symbolic = { version = "12.17.2", path = "../../symbolic", features = [
    "demangle",
] }
