name: Release build

on:
  push:
    branches:
      - "release/**"

env:
  MANYLINUX_VERSION: manylinux_2_28
  # Pinned to 2025.08.15-1 since manylinux 2025.08.22 onward removes setuptools
  MANYLINUX_PIN: 2025.08.15-1

jobs:
  python-wheel-mac:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            py-platform: macosx-10_15_x86_64
          - target: aarch64-apple-darwin
            py-platform: macosx-11_0_arm64

    name: Python macOS ${{ matrix.py-platform }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3 # v3 # v2

      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }} --no-self-update

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - run: make wheel PLATFORM=${{ matrix.py-platform }}
        env:
          # consumed by cargo and setup.py to obtain the target dir
          CARGO_BUILD_TARGET: ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-macos-${{ matrix.target }}
          path: py/dist/*
          if-no-files-found: "error"
          # since this artifact will be merged, compression is not necessary
          compression-level: "0"

  python-wheel-linux:
    strategy:
      fail-fast: false
      matrix:
        build-arch:
          - x86_64
          - aarch64

    name: Python Linux ${{ matrix.build-arch }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3 # v3 # v2

      - if: matrix.build-arch == 'aarch64'
        name: Build in Docker (aarch64)
        run: make wheel-manylinux-aarch64 IMAGE=messense/"$MANYLINUX_VERSION"-cross:aarch64-amd64

      - if: matrix.build-arch == 'x86_64'
        name: Build in Docker (x86_64)
        run: make wheel-manylinux IMAGE=quay.io/pypa/"$MANYLINUX_VERSION"_x86_64:"$MANYLINUX_PIN"

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-${{ matrix.build-arch }}
          path: py/dist/*
          if-no-files-found: "error"
          # since this artifact will be merged, compression is not necessary
          compression-level: "0"

  sdist:
    name: Python sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3 # v3 # v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - run: make sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: py/dist/*
          if-no-files-found: "error"
          # since this artifact will be merged, compression is not necessary
          compression-level: "0"

  merge:
    name: Create Release Artifact
    runs-on: ubuntu-latest
    needs: [python-wheel-linux, python-wheel-mac, sdist]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          # Craft expects release assets from github to be a single artifact named after the sha.
          name: ${{ github.sha }}
          pattern: artifact-*
          delete-merged: true
