[package]
name = "unreal_engine_crash"
version = "12.17.2"
authors = ["Jan Michael Auer <mail@jauer.org>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
symbolic = { version = "12.17.2", path = "../../symbolic", features = [
    "unreal",
] }
